spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/coffee
    username: postgres
    password: Khanhmy@0107!
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
